version: '3.9'

services:
  minio:
    extends:
      file: environment.yml
      service: common-vars
    image: bitnami/minio:latest
    volumes:
      - minio_data:/data
    expose:
      - 9000
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - storage.turnly.local
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.storage-public.tls=true

      - traefik.http.routers.storage-public.entrypoints=storage
      - traefik.http.routers.storage-public.service=storage-public
      - traefik.http.routers.storage-public.rule=Host(`${APP_INFRA_DOMAIN}`)
      - traefik.http.services.storage-public.loadbalancer.server.port=9001

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.storage-public.middlewares=oauth-admin-middleware

volumes:
  minio_data:
