version: '3.9'

services:
  gateway:
    extends:
      file: environment.yml
      service: common-vars
    image: ghcr.io/turnly/gateway:latest
    command:
      - --ping
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=turnly.network.internal

      # Default entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443

      # Global redirect to https
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      # Enable TLS Certificates
      - --certificatesresolvers.certs.acme.dnschallenge=true
      - --certificatesresolvers.certs.acme.dnschallenge.delaybeforecheck=90 # To delay DNS check and reduce LE hit rate
      - --certificatesresolvers.certs.acme.dnschallenge.provider=${TLS_DNS_PROVIDER}
      - --certificatesresolvers.certs.acme.email=${TLS_ISSUED_TO_EMAIL}
      - --certificatesresolvers.certs.acme.storage=/certs/data/acme.json

      # Optional - Expose monitoring and resource management services.
      # WARNING: If you enable these ports, you must take your own security measures.
      - --entrypoints.rabbitmq.address=:${RABBITMQ_UI_PORT}
      - --entrypoints.kibana.address=:${ELASTICSEARCH_UI_PORT}
      - --entrypoints.postgres.address=:${POSTGRES_ADMINER_PORT}
      - --entrypoints.mongo.address=:${MONGO_UI_PORT}
      - --entrypoints.redis.address=:${REDIS_UI_PORT}
      - --entrypoints.storage.address=:${MINIO_UI_PORT}
      - --entrypoints.tracing.address=:${TRACING_UI_PORT}
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      # Global wildcard certificates
      - traefik.http.routers.wildcard-certs.tls.certResolver=certs
      - traefik.http.routers.wildcard-certs.tls.domains[0].main=${APP_DOMAIN}
      - traefik.http.routers.wildcard-certs.tls.domains[0].sans=*.${APP_DOMAIN}
    environment:
      # NOTE: You must provide the required variables based on your DNS provider's configuration.
      # NOTE: See https://doc.traefik.io/traefik/https/acme
      DO_AUTH_TOKEN: ${DO_AUTH_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./etc/certs/data:/certs/data

      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443

      # Optional - Expose monitoring and resource management services.
      - ${RABBITMQ_UI_PORT}:${RABBITMQ_UI_PORT}
      - ${ELASTICSEARCH_UI_PORT}:${ELASTICSEARCH_UI_PORT}
      - ${POSTGRES_ADMINER_PORT}:${POSTGRES_ADMINER_PORT}
      - ${MONGO_UI_PORT}:${MONGO_UI_PORT}
      - ${REDIS_UI_PORT}:${REDIS_UI_PORT}
      - ${MINIO_UI_PORT}:${MINIO_UI_PORT}
      - ${TRACING_UI_PORT}:${TRACING_UI_PORT}
    healthcheck:
      test: ['CMD', 'traefik', 'healthcheck', '--ping']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - ${IAM_HOSTNAME}
          - ${APP_DOMAIN}

networks:
  turnly.network.internal:
    name: turnly.network.internal
  turnly.network.public:
    name: turnly.network.public