version: '3.9'

# Delete mongo.yml (this) file if you are using an external Mongo database
services:
  mongo:
    extends:
      file: environment.yml
      service: common-vars
    image: mongo:5.0.12
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    expose:
      - 27017
    volumes:
      - mongo_data:/data/db
      - ./etc/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    networks:
      turnly.network.internal:
        aliases:
          - mongo.turnly.local
    healthcheck:
      test: ['CMD', 'mongo', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
