version: '3.9'

# Delete mongo-ui.yml (this) file if you are using an external Mongo database
services:
  mongo_ui:
    extends:
      file: environment.yml
      service: common-vars
    image: mongo-express:latest
    networks:
      - turnly.network.public
      - turnly.network.internal
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.mongo-public.tls=true

      - traefik.http.routers.mongo-public.entrypoints=mongo
      - traefik.http.routers.mongo-public.service=mongo-public
      - traefik.http.routers.mongo-public.rule=Host(`${APP_INFRA_DOMAIN}`)
      - traefik.http.services.mongo-public.loadbalancer.server.port=8081

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.mongo-public.middlewares=oauth-admin-middleware
