version: '3.9'

# Delete postgres.yml (this) file if you are using an external Postgres provider
services:
  postgres:
    extends:
      file: environment.yml
      service: common-vars
    image: postgres:15.1-alpine
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      turnly.network.internal:
        aliases:
          - postgres.turnly.local
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
