version: "3.9"

services:
  server-error:
    image: tarampampam/error-pages:2.19.0
    environment:
      TEMPLATE_NAME: app-down
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.server-error.tls.certresolver=certs

      # use as "fallback" for any NON-registered services (with priority below normal)
      - traefik.http.routers.server-error.rule=HostRegexp(`{host:.+}`)
      - traefik.http.routers.server-error.priority=10

      - traefik.http.routers.server-error.entrypoints=websecure
      - traefik.http.routers.server-error.middlewares=server-error-middleware

      - traefik.http.middlewares.server-error-middleware.errors.status=400-599
      - traefik.http.middlewares.server-error-middleware.errors.service=server-error
      - traefik.http.middlewares.server-error-middleware.errors.query=/{status}.html

      - traefik.http.services.server-error.loadbalancer.server.port=8080
    depends_on:
      - gateway
    networks:
      - turnly.network.public
      - turnly.network.internal
