version: '3.9'

services:
  helpdesk-api:
    extends:
      file: environment.yml
      service: common-vars
    image: turnly/helpdesk-api:latest
    depends_on:
      iam:
        condition: service_healthy
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - helpdesk-api.turnly.local
    environment:
      APP_NAME: helpdesk-api
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      # These tags are used to enable authenticated access to the service via OAuth-middleware.
      - traefik.http.routers.helpdesk-api-public.entrypoints=web,websecure
      - traefik.http.routers.helpdesk-api-public.rule=PathPrefix(`/api/helpdesk`)
      - traefik.http.routers.helpdesk-api-public.service=helpdesk-api-public
      - traefik.http.services.helpdesk-api-public.loadbalancer.server.port=${APP_PORT}

      # Attach the OAuth-middleware to this service.
      - traefik.http.routers.helpdesk-api-public.middlewares=oauth-middleware
