version: '3.9'

services:
  oauth:
    extends:
      file: environment.yml
      service: oauth-vars
    image: turnly/oauth:${APP_VERSION}
    command: "./oauth --rule.public.action=allow --rule.public.rule=\"PathPrefix(`${PREFIX_UNAUTHENTICATED_ROUTES}`)\""
    depends_on:
      iam:
        condition: service_healthy
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - oauth.turnly.local
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.oauth-public.entrypoints=web,websecure
      - traefik.http.routers.oauth-public.service=oauth-public
      - traefik.http.routers.oauth-public.rule=Host(`${IAM_HOSTNAME}`) && Path(`/_oauth`)
      - traefik.http.services.oauth-public.loadbalancer.server.port=4181

      # Adding OAuth-middleware to traefik
      - traefik.http.middlewares.oauth-middleware.forwardauth.address=http://oauth.turnly.local:4181
      - traefik.http.middlewares.oauth-middleware.forwardauth.authResponseHeaders=X-Forwarded-User, X-Forwarded-Host, X-Forwarded-For, X-Forwarded-Uri, X-Forwarded-Auth-Token
      - traefik.http.middlewares.oauth-middleware.forwardauth.trustForwardHeader=true

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.oauth-public.middlewares=oauth-middleware

  oauth-admin:
    extends:
      file: environment.yml
      service: oauth-admin-vars
    image: turnly/oauth:${APP_VERSION}
    depends_on:
      iam:
        condition: service_healthy
    networks:
      turnly.network.public:
      turnly.network.internal:
        aliases:
          - oauth-admin.turnly.local
    labels:
      - traefik.enable=true
      - traefik.docker.network=turnly.network.internal

      - traefik.http.routers.oauth-admin-public.entrypoints=web,websecure
      - traefik.http.routers.oauth-admin-public.service=oauth-admin-public
      - traefik.http.routers.oauth-admin-public.rule=Host(`${IAM_HOSTNAME}`) && Path(`/_oauth-admin`)
      - traefik.http.services.oauth-admin-public.loadbalancer.server.port=4181

      # Adding OAuth-middleware to traefik
      - traefik.http.middlewares.oauth-admin-middleware.forwardauth.address=http://oauth-admin.turnly.local:4181
      - traefik.http.middlewares.oauth-admin-middleware.forwardauth.authResponseHeaders=X-Forwarded-User, X-Forwarded-Host, X-Forwarded-For, X-Forwarded-Uri, X-Forwarded-Auth-Token
      - traefik.http.middlewares.oauth-admin-middleware.forwardauth.trustForwardHeader=true

      # Attach the OAuth-middleware to this service
      - traefik.http.routers.oauth-admin-public.middlewares=oauth-admin-middleware
