name: 🚀 CD - Assistance Centers Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying assistance-centers service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s assistance-centers --force
