name: 🚀 CD - Business Owners Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying business-owners service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s business-owners --force
