name: 🚀 CD - Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: stage
    steps:
      - name: 📦 Pulling changes from Compose Operator...
        run: cd /opt/turnly && git pull origin main

      - name: 📡 Upgrading Apps services...
        run: cd /opt/turnly && bash compose.sh upgrade --force
