name: 🚀 CD - Custom Fields Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying custom-fields service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s custom-fields --force
