name: 🚀 CD - Global Continuous Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/workflows/continuous-deployment.yml'
      - '!README.md'
    branches:
      - main

jobs:
  deployment:
    runs-on: stage
    steps:
      - name: 📦 Pulling changes from Compose Operator...
        run: cd /opt/turnly && git pull origin main

      - name: 📡 Upgrading Apps services...
        run: cd /opt/turnly && bash compose.sh upgrade --force
