name: 🚀 CD - Global Continuous Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - '**'
      - '!.github/workflows/continuous-deployment.yml'
      - '!README.md'
    branches:
      - main

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying all services...
        run: |
          git pull origin main
          bash compose.sh upgrade --force
