name: 🚀 CD - Helpdesk API Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying helpdesk-api service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s helpdesk-api --force
