name: 🚀 CD - OAuth Middle Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying oauth service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s oauth -s oauth-admin --force
