name: 🚀 CD - Queuing System Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying queuing-system service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s queuing-system --force
