name: 🚀 CD - Teams Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying teams service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s teams --force
