name: 🚀 CD - Widgets Realtime API Continuous Deployment

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: stage
    defaults:
      run:
        working-directory: /opt/turnly
    steps:
      - name: 📡 Deploying widgets-realtime-api service...
        run: |
          git pull origin main
          bash compose.sh upgrade -s widgets-realtime-api --force
